
from enum import Enum


class ParserState(Enum):
    HEADER = 'HEADER'
    HEADER_COLON = 'HEADER_COLON'
    HEADER_VALUE = 'HEADER_VALUE'
    GROUP_EVENT = 'GROUP_EVENT'
    GROUP_NEXT_STATE = 'GROUP_NEXT_STATE'
    STATE_SPEC = 'STATE_SPEC'
    STATE_MODIFIER = 'STATE_MODIFIER'
    ENTRY_ACTION = 'ENTRY_ACTION'
    EXIT_ACTION = 'EXIT_ACTION'
    MULTIPLE_ENTRY_ACTIONS = 'MULTIPLE_ENTRY_ACTIONS'
    MULTIPLE_EXIT_ACTIONS = 'MULTIPLE_EXIT_ACTIONS'
    STATE_BASE = 'STATE_BASE'
    SINGLE_EVENT = 'SINGLE_EVENT'
    SINGLE_NEXT_STATE = 'SINGLE_NEXT_STATE'
    SINGLE_ACTION_GROUP = 'SINGLE_ACTION_GROUP'
    SINGLE_ACTION_GROUP_NAME = 'SINGLE_ACTION_GROUP_NAME'
    SUBTRANSITION_GROUP = 'SUBTRANSITION_GROUP'
    SUPER_STATE_NAME = 'SUPER_STATE_NAME'
    SUPER_STATE_CLOSE = 'SUPER_STATE_CLOSE'
    GROUP_ACTION_GROUP = 'GROUP_ACTION_GROUP'
    GROUP_ACTION_GROUP_NAME = 'GROUP_ACTION_GROUP_NAME'
    END = 'END'